import { useState, useEffect, useRef } from "react";
import { createPortal } from "react-dom";
import { useParams, useNavigate } from "react-router-dom";
import {
  ArrowLeft,
  Power,
  Trash2,
  Zap,
  Target,
  Search,
  ArrowUpDown,
  ArrowUp,
  ArrowDown,
  Info,
} from "lucide-react";
import { useStrategy, useToggleStrategy, useDeleteStrategy } from "@/hooks/useStrategies";
import { useSignals } from "@/hooks/useSignals";
import { useTradeStats } from "@/hooks/useTrades";
import { useRunStrategyBacktest } from "@/hooks/useStrategyBacktest";
import { StrategyBacktestForm } from "@/components/backtest/StrategyBacktestForm";
import { StrategyBacktestResults } from "@/components/backtest/StrategyBacktestResults";
import { Tooltip } from "@/components/ui/Tooltip";
import { Badge } from "@/components/ui/Badge";
import { Pagination } from "@/components/ui/Pagination";
import type { Signal } from "@/hooks/useSignals";
import type { StrategyBacktestResult } from "@/hooks/useStrategyBacktest";
import { cn } from "@/lib/cn";
import { formatPrice } from "@/lib/format";

const PAGE_SIZE = 20;

type Tab = "signals" | "strategy";

const TABS: { key: Tab; label: string; icon: typeof Zap; tip: string }[] = [
  { key: "signals", label: "Signals", icon: Zap, tip: "View all signals generated by this strategy." },
  { key: "strategy", label: "Strategy Validation", icon: Target, tip: "Validate this strategy against historical data across all its symbols." },
];

/* ----- Helpers ----- */

function formatTime(dateStr: string): string {
  const d = new Date(dateStr);
  return d.toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  });
}

function ConfluenceBar({ score }: { score: number }) {
  const pct = Math.min(100, Math.max(0, score));
  let color = "bg-[var(--color-negative)]";
  if (pct >= 60) color = "bg-[var(--color-positive)]";
  else if (pct >= 30) color = "bg-[var(--color-warning)]";

  return (
    <div className="flex items-center gap-2">
      <div className="w-16 h-1.5 rounded-full bg-[var(--color-bg-elevated)] overflow-hidden">
        <div className={`h-full rounded-full transition-all ${color}`} style={{ width: `${pct}%` }} />
      </div>
      <span className="text-xs font-mono text-[var(--color-text-secondary)]">{score}</span>
    </div>
  );
}

const TRIGGER_LABELS: Record<string, string> = {
  macd_crossover: "MACD crossover",
  rsi_midline_cross: "RSI midline cross",
  engulfing_candle: "Engulfing candle",
  zone_reclaim: "Zone reclaim",
  stochastic_exit_extreme: "Stochastic extreme exit",
  bollinger_squeeze: "Bollinger squeeze",
  volume_spike: "Volume spike",
};

/* ----- Signal Reasoning Tooltip (hover) ----- */

function SignalReasoningTooltip({ signal }: { signal: Signal }) {
  const [show, setShow] = useState(false);
  const triggerRef = useRef<HTMLSpanElement>(null);
  const hideTimer = useRef<number>(0);

  const handleEnter = () => { clearTimeout(hideTimer.current); setShow(true); };
  const handleLeave = () => { hideTimer.current = window.setTimeout(() => setShow(false), 120); };

  const hasInfo = signal.ai_reasoning || signal.triggers?.length || signal.regime || signal.mtf_alignment;
  if (!hasInfo) {
    return <span className="text-(--color-text-secondary)/40"><Info className="w-3.5 h-3.5" /></span>;
  }

  let tooltipStyle: React.CSSProperties = {};
  if (show && triggerRef.current) {
    const rect = triggerRef.current.getBoundingClientRect();
    const openUp = rect.top > window.innerHeight / 2;
    tooltipStyle = {
      right: Math.max(8, window.innerWidth - rect.right),
      ...(openUp
        ? { bottom: window.innerHeight - rect.top + 6 }
        : { top: rect.bottom + 6 }),
    };
  }

  return (
    <div className="relative inline-flex" onMouseEnter={handleEnter} onMouseLeave={handleLeave}>
      <span
        ref={triggerRef}
        className={cn(
          "p-0.5 rounded transition-colors cursor-help",
          signal.ai_recommendation === "confirm"
            ? "text-(--color-positive) hover:bg-(--color-positive)/10"
            : signal.ai_recommendation === "caution"
              ? "text-(--color-warning) hover:bg-(--color-warning)/10"
              : signal.ai_recommendation === "reject"
                ? "text-(--color-negative) hover:bg-(--color-negative)/10"
                : "text-(--color-text-secondary) hover:bg-(--color-bg-elevated)",
        )}
      >
        <Info className="w-3.5 h-3.5" />
      </span>
      {show && createPortal(
        <div
          className="fixed z-[200] w-80 bg-(--color-bg-surface) border border-(--color-border) rounded-lg shadow-xl p-3 text-xs space-y-2"
          style={tooltipStyle}
          onMouseEnter={handleEnter}
          onMouseLeave={handleLeave}
        >
          {/* Signal context */}
          <div>
            <p className="font-semibold text-(--color-text-primary) mb-1">
              {signal.direction.toUpperCase()} {signal.symbol}
            </p>
            <p className="text-(--color-text-secondary)">
              <span className="font-medium">Regime:</span>{" "}
              <span className="capitalize">{signal.regime}</span>
            </p>
            {signal.triggers && signal.triggers.length > 0 && (
              <p className="text-(--color-text-secondary)">
                <span className="font-medium">Triggers:</span>{" "}
                {signal.triggers.map((t) => TRIGGER_LABELS[t] || t).join(", ")}
              </p>
            )}
            <p className="text-(--color-text-secondary)">
              <span className="font-medium">Confluence:</span> {signal.confluence_score}/100
            </p>
            {signal.mtf_alignment && (
              <p className="text-(--color-text-secondary)">
                <span className="font-medium">MTF:</span>{" "}
                <span className="capitalize">{signal.mtf_alignment}</span>
                {signal.mtf_confidence != null && ` (${signal.mtf_confidence}%)`}
              </p>
            )}
          </div>

          {/* AI assessment */}
          {(signal.ai_quality_score != null || signal.ai_reasoning) && (
            <div className="border-t border-(--color-border) pt-2">
              <p className="font-semibold text-(--color-text-primary) mb-1 flex items-center gap-1.5">
                AI Assessment
                {signal.ai_recommendation && (
                  <span
                    className={cn(
                      "px-1.5 py-0.5 rounded text-[10px] font-bold uppercase",
                      signal.ai_recommendation === "confirm"
                        ? "bg-(--color-positive)/15 text-(--color-positive)"
                        : signal.ai_recommendation === "caution"
                          ? "bg-(--color-warning)/15 text-(--color-warning)"
                          : "bg-(--color-negative)/15 text-(--color-negative)",
                    )}
                  >
                    {signal.ai_recommendation}
                  </span>
                )}
                {signal.ai_quality_score != null && (
                  <span className="text-(--color-text-secondary) font-normal">
                    (score: {signal.ai_quality_score})
                  </span>
                )}
              </p>
              {signal.ai_reasoning && (
                <p className="text-(--color-text-secondary) leading-relaxed">
                  {signal.ai_reasoning}
                </p>
              )}
            </div>
          )}
        </div>,
        document.body,
      )}
    </div>
  );
}

/* ----- Sortable Header ----- */

type SortKey = "created_at" | "symbol" | "direction" | "entry_price" | "confluence_score" | "status" | "ai_quality_score";

function SortHeader({
  label,
  sortKey,
  current,
  dir,
  onSort,
  align,
}: {
  label: string;
  sortKey: SortKey;
  current: SortKey;
  dir: "asc" | "desc";
  onSort: (key: SortKey) => void;
  align?: string;
}) {
  const isActive = current === sortKey;
  const Icon = isActive ? (dir === "asc" ? ArrowUp : ArrowDown) : ArrowUpDown;
  return (
    <th
      onClick={() => onSort(sortKey)}
      className={cn(
        "px-3 py-2.5 text-xs font-semibold uppercase tracking-wider whitespace-nowrap cursor-pointer select-none transition-colors hover:text-(--color-text-primary)",
        isActive ? "text-(--color-accent)" : "text-(--color-text-secondary)",
        align,
      )}
    >
      <span className="inline-flex items-center gap-1">
        {label}
        <Icon className="w-3 h-3" />
      </span>
    </th>
  );
}

/* ----- Skeleton Row ----- */

function SkeletonRow() {
  return (
    <tr>
      {Array.from({ length: 11 }).map((_, i) => (
        <td key={i} className="px-3 py-3">
          <div className="h-4 bg-(--color-bg-elevated) rounded animate-pulse" />
        </td>
      ))}
    </tr>
  );
}

/* ----- Filter Select ----- */

const selectClasses =
  "h-8 rounded-lg border border-(--color-border) bg-(--color-bg-surface) px-2.5 text-xs text-(--color-text-primary) focus:outline-none focus:ring-1 focus:ring-(--color-accent) appearance-none cursor-pointer";

/* ----- Main Page ----- */
export function StrategyDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<Tab>("signals");
  const [signalOffset, setSignalOffset] = useState(0);
  const [showConfirm, setShowConfirm] = useState(false);

  // Signal filters
  const [searchInput, setSearchInput] = useState("");
  const [debouncedSearch, setDebouncedSearch] = useState("");
  const [dirFilter, setDirFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [sortBy, setSortBy] = useState<SortKey>("created_at");
  const [sortDir, setSortDir] = useState<"asc" | "desc">("desc");

  // Debounce search input
  useEffect(() => {
    const t = setTimeout(() => {
      setDebouncedSearch(searchInput);
      setSignalOffset(0);
    }, 300);
    return () => clearTimeout(t);
  }, [searchInput]);

  const { data: strategy, isLoading: strategyLoading } = useStrategy(id!);
  const { data: signalData, isLoading: signalsLoading } = useSignals({
    limit: PAGE_SIZE,
    offset: signalOffset,
    strategyId: id,
    symbol: debouncedSearch || undefined,
    direction: dirFilter || undefined,
    status: statusFilter || undefined,
    sortBy,
    sortDir,
  });
  const { data: stats } = useTradeStats(id);
  const toggleMutation = useToggleStrategy();
  const deleteMutation = useDeleteStrategy();

  const strategyBtMutation = useRunStrategyBacktest();
  const strategyBtResult = (strategyBtMutation.data as StrategyBacktestResult) ?? null;

  const handleSort = (key: SortKey) => {
    if (sortBy === key) {
      setSortDir((d) => (d === "asc" ? "desc" : "asc"));
    } else {
      setSortBy(key);
      setSortDir("desc");
    }
    setSignalOffset(0);
  };

  if (strategyLoading) {
    return (
      <div className="p-6 space-y-6 max-w-[1600px] mx-auto">
        <div className="h-8 w-48 bg-(--color-bg-elevated) rounded animate-pulse" />
        <div className="h-32 bg-(--color-bg-surface) border border-(--color-border) rounded-xl animate-pulse" />
      </div>
    );
  }

  if (!strategy) {
    return (
      <div className="p-6 space-y-4 max-w-[1600px] mx-auto">
        <button
          onClick={() => navigate("/strategies")}
          className="flex items-center gap-1.5 text-sm text-(--color-text-secondary) hover:text-(--color-text-primary) transition-colors"
        >
          <ArrowLeft className="w-4 h-4" /> Back to Strategies
        </button>
        <div className="bg-(--color-bg-surface) border border-(--color-border) rounded-xl p-12 text-center">
          <p className="text-sm text-(--color-text-secondary)">Strategy not found.</p>
        </div>
      </div>
    );
  }

  const config = (strategy.config ?? {}) as Record<string, unknown>;
  const symbols = (config.symbols as string[]) ?? [];

  const handleDelete = () => {
    deleteMutation.mutate(strategy.id, {
      onSuccess: () => navigate("/strategies"),
    });
  };

  const signals = signalData?.signals ?? [];
  const signalTotal = signalData?.total ?? 0;

  return (
    <div className="p-6 space-y-6 max-w-[1600px] mx-auto">
      {/* Back link */}
      <button
        onClick={() => navigate("/strategies")}
        className="flex items-center gap-1.5 text-sm text-(--color-text-secondary) hover:text-(--color-text-primary) transition-colors"
      >
        <ArrowLeft className="w-4 h-4" /> Back to Strategies
      </button>

      {/* Strategy header */}
      <div className="bg-(--color-bg-surface) border border-(--color-border) rounded-xl p-5">
        <div className="flex items-start justify-between gap-4">
          <div>
            <div className="flex items-center gap-2.5">
              <h1 className="text-xl font-bold text-(--color-text-primary)">
                {strategy.name}
              </h1>
              <span
                className={cn(
                  "inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-semibold uppercase",
                  strategy.is_active
                    ? "bg-(--color-positive)/10 text-(--color-positive)"
                    : "bg-(--color-bg-elevated) text-(--color-text-secondary)",
                )}
              >
                <span
                  className={cn(
                    "w-1.5 h-1.5 rounded-full",
                    strategy.is_active ? "bg-(--color-positive)" : "bg-(--color-text-secondary)/40",
                  )}
                />
                {strategy.is_active ? "Active" : "Inactive"}
              </span>
            </div>
            {symbols.length > 0 && (
              <div className="flex flex-wrap gap-1.5 mt-2">
                {symbols.map((s) => (
                  <span
                    key={s}
                    className="text-[11px] bg-(--color-accent-soft) text-(--color-accent) rounded-md px-2 py-0.5 font-medium"
                  >
                    {s}
                  </span>
                ))}
              </div>
            )}
          </div>

          <div className="flex items-center gap-1.5 shrink-0">
            <button
              onClick={() => toggleMutation.mutate(strategy.id)}
              disabled={toggleMutation.isPending}
              className={cn(
                "flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors",
                strategy.is_active
                  ? "bg-(--color-negative)/10 text-(--color-negative) hover:bg-(--color-negative)/20"
                  : "bg-(--color-positive)/10 text-(--color-positive) hover:bg-(--color-positive)/20",
              )}
            >
              <Power className="w-3.5 h-3.5" />
              {strategy.is_active ? "Deactivate" : "Activate"}
            </button>
            {showConfirm ? (
              <div className="flex items-center gap-1 ml-1">
                <button
                  onClick={handleDelete}
                  disabled={deleteMutation.isPending}
                  className="px-2.5 py-1.5 rounded-lg text-xs font-medium bg-(--color-negative)/10 text-(--color-negative) hover:bg-(--color-negative)/20 transition-colors"
                >
                  {deleteMutation.isPending ? "..." : "Confirm Delete"}
                </button>
                <button
                  onClick={() => setShowConfirm(false)}
                  className="px-2.5 py-1.5 rounded-lg text-xs text-(--color-text-secondary) hover:bg-(--color-bg-elevated) transition-colors"
                >
                  Cancel
                </button>
              </div>
            ) : (
              <button
                onClick={() => setShowConfirm(true)}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-(--color-text-secondary) hover:bg-(--color-negative)/10 hover:text-(--color-negative) transition-colors"
              >
                <Trash2 className="w-3.5 h-3.5" />
                Delete
              </button>
            )}
          </div>
        </div>

        {/* Performance summary */}
        {stats && stats.total_trades > 0 && (
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4 pt-4 border-t border-(--color-border)/50">
            <div className="bg-(--color-bg-elevated)/50 rounded-lg px-3 py-2">
              <p className="text-[10px] text-(--color-text-secondary)">Total P&L</p>
              <p className={cn(
                "text-sm font-semibold font-mono",
                stats.total_pnl >= 0 ? "text-(--color-positive)" : "text-(--color-negative)",
              )}>
                {stats.total_pnl >= 0 ? "+" : ""}${stats.total_pnl.toFixed(2)}
              </p>
            </div>
            <div className="bg-(--color-bg-elevated)/50 rounded-lg px-3 py-2">
              <p className="text-[10px] text-(--color-text-secondary)">Win Rate</p>
              <div className="flex items-center gap-1">
                <Target className="w-3 h-3 text-(--color-accent)" />
                <p className="text-sm font-semibold font-mono text-(--color-text-primary)">
                  {stats.win_rate.toFixed(1)}%
                </p>
              </div>
            </div>
            <div className="bg-(--color-bg-elevated)/50 rounded-lg px-3 py-2">
              <p className="text-[10px] text-(--color-text-secondary)">Trades</p>
              <p className="text-sm font-semibold font-mono text-(--color-text-primary)">
                {stats.total_trades}
              </p>
            </div>
            <div className="bg-(--color-bg-elevated)/50 rounded-lg px-3 py-2">
              <p className="text-[10px] text-(--color-text-secondary)">Profit Factor</p>
              <p className={cn(
                "text-sm font-semibold font-mono",
                stats.profit_factor >= 1 ? "text-(--color-positive)" : "text-(--color-negative)",
              )}>
                {Number.isFinite(stats.profit_factor) ? stats.profit_factor.toFixed(2) : "\u221E"}
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Tab bar */}
      <div className="border-b border-(--color-border)">
        <div className="flex gap-6">
          {TABS.map((tab) => {
            const Icon = tab.icon;
            return (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key)}
                className={cn(
                  "pb-2.5 text-sm font-medium transition-colors border-b-2 -mb-px flex items-center gap-1.5",
                  activeTab === tab.key
                    ? "border-(--color-accent) text-(--color-accent)"
                    : "border-transparent text-(--color-text-secondary) hover:text-(--color-text-primary)",
                )}
              >
                <Icon className="w-3.5 h-3.5" />
                {tab.label}
                <Tooltip icon text={tab.tip} />
              </button>
            );
          })}
        </div>
      </div>

      {/* Tab content */}
      {activeTab === "signals" && (
        <div className="space-y-3">
          {/* Filter toolbar */}
          <div className="flex items-center gap-3 flex-wrap">
            <div className="relative">
              <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-(--color-text-secondary) pointer-events-none" />
              <input
                type="text"
                placeholder="Search symbol..."
                value={searchInput}
                onChange={(e) => setSearchInput(e.target.value)}
                className="h-8 w-44 rounded-lg border border-(--color-border) bg-(--color-bg-surface) pl-8 pr-3 text-xs text-(--color-text-primary) placeholder:text-(--color-text-secondary)/60 focus:outline-none focus:ring-1 focus:ring-(--color-accent)"
              />
            </div>
            <select
              value={dirFilter}
              onChange={(e) => { setDirFilter(e.target.value); setSignalOffset(0); }}
              className={selectClasses}
            >
              <option value="">All Directions</option>
              <option value="BUY">BUY</option>
              <option value="SELL">SELL</option>
            </select>
            <select
              value={statusFilter}
              onChange={(e) => { setStatusFilter(e.target.value); setSignalOffset(0); }}
              className={selectClasses}
            >
              <option value="">All Statuses</option>
              <option value="active">Active</option>
              <option value="rejected">Rejected</option>
              <option value="filled">Filled</option>
              <option value="expired">Expired</option>
              <option value="pending">Pending</option>
            </select>
            {(debouncedSearch || dirFilter || statusFilter) && (
              <button
                onClick={() => { setSearchInput(""); setDirFilter(""); setStatusFilter(""); setSignalOffset(0); }}
                className="h-8 px-2.5 rounded-lg text-xs text-(--color-text-secondary) hover:text-(--color-text-primary) hover:bg-(--color-bg-elevated) transition-colors"
              >
                Clear filters
              </button>
            )}
            <span className="ml-auto text-xs text-(--color-text-secondary) tabular-nums">
              {signalTotal} signal{signalTotal !== 1 ? "s" : ""}
            </span>
          </div>

          {/* Signals table */}
          <div className="bg-(--color-bg-surface) border border-(--color-border) rounded-xl overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-left text-sm min-w-[1000px]">
                <thead>
                  <tr className="border-b border-(--color-border) bg-(--color-bg-elevated)/50">
                    <SortHeader label="Time" sortKey="created_at" current={sortBy} dir={sortDir} onSort={handleSort} />
                    <SortHeader label="Symbol" sortKey="symbol" current={sortBy} dir={sortDir} onSort={handleSort} />
                    <SortHeader label="Direction" sortKey="direction" current={sortBy} dir={sortDir} onSort={handleSort} />
                    <SortHeader label="Entry" sortKey="entry_price" current={sortBy} dir={sortDir} onSort={handleSort} align="text-right" />
                    <th className="px-3 py-2.5 text-xs font-semibold text-(--color-text-secondary) uppercase tracking-wider text-right">SL</th>
                    <th className="px-3 py-2.5 text-xs font-semibold text-(--color-text-secondary) uppercase tracking-wider text-right">TP1</th>
                    <th className="px-3 py-2.5 text-xs font-semibold text-(--color-text-secondary) uppercase tracking-wider text-right">Size</th>
                    <SortHeader label="Confluence" sortKey="confluence_score" current={sortBy} dir={sortDir} onSort={handleSort} />
                    <th className="px-3 py-2.5 text-xs font-semibold text-(--color-text-secondary) uppercase tracking-wider">Regime</th>
                    <SortHeader label="Status" sortKey="status" current={sortBy} dir={sortDir} onSort={handleSort} />
                    <th className="px-3 py-2.5 text-xs font-semibold text-(--color-text-secondary) uppercase tracking-wider text-center whitespace-nowrap">Info</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-(--color-border)/50">
                  {signalsLoading ? (
                    Array.from({ length: 8 }).map((_, i) => <SkeletonRow key={i} />)
                  ) : signals.length === 0 ? (
                    <tr>
                      <td colSpan={11} className="px-3 py-16 text-center text-(--color-text-secondary)">
                        {debouncedSearch || dirFilter || statusFilter
                          ? "No signals match your filters."
                          : "No signals generated by this strategy yet."}
                      </td>
                    </tr>
                  ) : (
                    signals.map((s) => <SignalRow key={s.id} signal={s} />)
                  )}
                </tbody>
              </table>
            </div>

            {signalTotal > PAGE_SIZE && (
              <div className="border-t border-(--color-border)">
                <Pagination
                  total={signalTotal}
                  limit={PAGE_SIZE}
                  offset={signalOffset}
                  onChange={setSignalOffset}
                />
              </div>
            )}
          </div>
        </div>
      )}

      {activeTab === "strategy" && (
        <div className="grid grid-cols-1 lg:grid-cols-[minmax(280px,35%)_1fr] gap-6">
          <StrategyBacktestForm
            onSubmit={(req) => strategyBtMutation.mutate(req)}
            isLoading={strategyBtMutation.isPending}
            prefillStrategyId={strategy.id}
          />
          <StrategyBacktestResults
            result={strategyBtResult}
            isLoading={strategyBtMutation.isPending}
            error={strategyBtMutation.error}
          />
        </div>
      )}
    </div>
  );
}

/* ----- Signal Row ----- */

function SignalRow({ signal }: { signal: Signal }) {
  const isBuy = signal.direction.toUpperCase() === "BUY";
  const statusLower = signal.status.toLowerCase();

  let statusVariant: "success" | "danger" | "warning" | "neutral" = "neutral";
  if (statusLower === "active" || statusLower === "filled") statusVariant = "success";
  else if (statusLower === "cancelled" || statusLower === "expired" || statusLower === "rejected") statusVariant = "danger";
  else if (statusLower === "pending") statusVariant = "warning";

  const regimeLower = signal.regime.toLowerCase();
  let regimeVariant: "success" | "danger" | "warning" | "info" | "neutral" = "neutral";
  if (regimeLower === "trending" || regimeLower === "bullish") regimeVariant = "success";
  else if (regimeLower === "bearish" || regimeLower === "crisis") regimeVariant = "danger";
  else if (regimeLower === "volatile" || regimeLower === "mixed") regimeVariant = "warning";
  else if (regimeLower === "mean_reverting") regimeVariant = "info";

  return (
    <tr className="hover:bg-(--color-bg-elevated)/50 transition-colors">
      <td className="px-3 py-2.5 text-xs text-(--color-text-secondary) whitespace-nowrap">
        {formatTime(signal.created_at)}
      </td>
      <td className="px-3 py-2.5 font-semibold text-(--color-text-primary) whitespace-nowrap">
        {signal.symbol}
      </td>
      <td className="px-3 py-2.5">
        <Badge variant={isBuy ? "success" : "danger"}>
          {signal.direction.toUpperCase()}
        </Badge>
      </td>
      <td className="px-3 py-2.5 font-mono tabular-nums text-right whitespace-nowrap">
        {formatPrice(signal.entry_price)}
      </td>
      <td className="px-3 py-2.5 font-mono tabular-nums text-(--color-text-secondary) text-right whitespace-nowrap">
        {formatPrice(signal.stop_loss)}
      </td>
      <td className="px-3 py-2.5 font-mono tabular-nums text-(--color-text-secondary) text-right whitespace-nowrap">
        {formatPrice(signal.take_profit_1)}
      </td>
      <td className="px-3 py-2.5 font-mono tabular-nums text-(--color-text-secondary) text-right whitespace-nowrap">
        {signal.position_size != null ? signal.position_size.toFixed(4) : "--"}
      </td>
      <td className="px-3 py-2.5">
        <ConfluenceBar score={signal.confluence_score} />
      </td>
      <td className="px-3 py-2.5">
        <Badge variant={regimeVariant}>{signal.regime}</Badge>
      </td>
      <td className="px-3 py-2.5">
        <Badge variant={statusVariant}>{signal.status}</Badge>
      </td>
      <td className="px-3 py-2.5 text-center">
        <SignalReasoningTooltip signal={signal} />
      </td>
    </tr>
  );
}
