import { useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import {
  ArrowLeft,
  Power,
  Trash2,
  Zap,
  Target,
} from "lucide-react";
import { useStrategy, useToggleStrategy, useDeleteStrategy } from "@/hooks/useStrategies";
import { useSignals } from "@/hooks/useSignals";
import { useTradeStats } from "@/hooks/useTrades";
import { useRunStrategyBacktest } from "@/hooks/useStrategyBacktest";
import { StrategyBacktestForm } from "@/components/backtest/StrategyBacktestForm";
import { StrategyBacktestResults } from "@/components/backtest/StrategyBacktestResults";
import { Tooltip } from "@/components/ui/Tooltip";
import { Badge } from "@/components/ui/Badge";
import { DataTable } from "@/components/ui/DataTable";
import { Pagination } from "@/components/ui/Pagination";
import type { Column } from "@/components/ui/DataTable";
import type { Signal } from "@/hooks/useSignals";
import type { StrategyBacktestResult } from "@/hooks/useStrategyBacktest";
import { cn } from "@/lib/cn";
import { formatPrice } from "@/lib/format";

const PAGE_SIZE = 20;

type Tab = "signals" | "strategy";

const TABS: { key: Tab; label: string; icon: typeof Zap; tip: string }[] = [
  { key: "signals", label: "Signals", icon: Zap, tip: "View all signals generated by this strategy." },
  { key: "strategy", label: "Strategy Validation", icon: Target, tip: "Validate this strategy against historical data across all its symbols." },
];

/* ----- Signal table helpers ----- */

function formatTime(dateStr: string): string {
  const d = new Date(dateStr);
  return d.toLocaleString("en-US", {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  });
}

function ConfluenceBar({ score }: { score: number }) {
  const pct = Math.min(100, Math.max(0, score));
  let color = "bg-[var(--color-negative)]";
  if (pct >= 60) color = "bg-[var(--color-positive)]";
  else if (pct >= 30) color = "bg-[var(--color-warning)]";

  return (
    <div className="flex items-center gap-2">
      <div className="w-16 h-1.5 rounded-full bg-[var(--color-bg-elevated)] overflow-hidden">
        <div className={`h-full rounded-full transition-all ${color}`} style={{ width: `${pct}%` }} />
      </div>
      <span className="text-xs font-mono text-[var(--color-text-secondary)]">{score}</span>
    </div>
  );
}

type SignalRow = Signal & Record<string, unknown>;

const signalColumns: Column<SignalRow>[] = [
  { key: "created_at", header: "Time", render: (row) => <span className="text-xs text-[var(--color-text-secondary)] whitespace-nowrap">{formatTime(row.created_at)}</span> },
  { key: "symbol", header: "Symbol", render: (row) => <span className="font-semibold text-[var(--color-text-primary)]">{row.symbol}</span> },
  { key: "direction", header: "Direction", render: (row) => <Badge variant={row.direction.toUpperCase() === "LONG" ? "success" : "danger"}>{row.direction.toUpperCase()}</Badge> },
  { key: "entry_price", header: "Entry", align: "right", render: (row) => <span className="font-mono">{formatPrice(row.entry_price)}</span> },
  { key: "stop_loss", header: "SL", align: "right", render: (row) => <span className="font-mono text-[var(--color-text-secondary)]">{formatPrice(row.stop_loss)}</span> },
  { key: "take_profit_1", header: "TP1", align: "right", render: (row) => <span className="font-mono text-[var(--color-text-secondary)]">{formatPrice(row.take_profit_1)}</span> },
  { key: "position_size", header: "Size", align: "right" as const, render: (row: SignalRow) => <span className="font-mono text-[var(--color-text-secondary)]">{row.position_size != null ? row.position_size.toFixed(4) : "--"}</span> },
  { key: "confluence_score", header: "Confluence", render: (row) => <ConfluenceBar score={row.confluence_score} /> },
  { key: "regime", header: "Regime", render: (row) => {
    const r = row.regime.toLowerCase();
    let variant: "success" | "danger" | "warning" | "info" | "neutral" = "neutral";
    if (r === "trending" || r === "bullish") variant = "success";
    else if (r === "bearish" || r === "crisis") variant = "danger";
    else if (r === "volatile" || r === "mixed") variant = "warning";
    else if (r === "mean_reverting") variant = "info";
    return <Badge variant={variant}>{row.regime}</Badge>;
  }},
  { key: "status", header: "Status", render: (row) => {
    const s = row.status.toLowerCase();
    let variant: "success" | "danger" | "warning" | "info" | "neutral" = "neutral";
    if (s === "active" || s === "filled") variant = "success";
    else if (s === "cancelled" || s === "expired" || s === "rejected") variant = "danger";
    else if (s === "pending") variant = "warning";
    return <Badge variant={variant}>{row.status}</Badge>;
  }},
];

/* ----- Main Page ----- */
export function StrategyDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<Tab>("signals");
  const [signalOffset, setSignalOffset] = useState(0);
  const [showConfirm, setShowConfirm] = useState(false);

  const { data: strategy, isLoading: strategyLoading } = useStrategy(id!);
  const { data: signalData, isLoading: signalsLoading } = useSignals(PAGE_SIZE, signalOffset, id);
  const { data: stats } = useTradeStats(id);
  const toggleMutation = useToggleStrategy();
  const deleteMutation = useDeleteStrategy();

  const strategyBtMutation = useRunStrategyBacktest();
  const strategyBtResult = (strategyBtMutation.data as StrategyBacktestResult) ?? null;

  if (strategyLoading) {
    return (
      <div className="p-6 space-y-6 max-w-[1600px] mx-auto">
        <div className="h-8 w-48 bg-(--color-bg-elevated) rounded animate-pulse" />
        <div className="h-32 bg-(--color-bg-surface) border border-(--color-border) rounded-xl animate-pulse" />
      </div>
    );
  }

  if (!strategy) {
    return (
      <div className="p-6 space-y-4 max-w-[1600px] mx-auto">
        <button
          onClick={() => navigate("/strategies")}
          className="flex items-center gap-1.5 text-sm text-(--color-text-secondary) hover:text-(--color-text-primary) transition-colors"
        >
          <ArrowLeft className="w-4 h-4" /> Back to Strategies
        </button>
        <div className="bg-(--color-bg-surface) border border-(--color-border) rounded-xl p-12 text-center">
          <p className="text-sm text-(--color-text-secondary)">Strategy not found.</p>
        </div>
      </div>
    );
  }

  const config = (strategy.config ?? {}) as Record<string, unknown>;
  const symbols = (config.symbols as string[]) ?? [];

  const handleDelete = () => {
    deleteMutation.mutate(strategy.id, {
      onSuccess: () => navigate("/strategies"),
    });
  };

  const signals = (signalData?.signals ?? []) as SignalRow[];
  const signalTotal = signalData?.total ?? 0;

  return (
    <div className="p-6 space-y-6 max-w-[1600px] mx-auto">
      {/* Back link */}
      <button
        onClick={() => navigate("/strategies")}
        className="flex items-center gap-1.5 text-sm text-(--color-text-secondary) hover:text-(--color-text-primary) transition-colors"
      >
        <ArrowLeft className="w-4 h-4" /> Back to Strategies
      </button>

      {/* Strategy header */}
      <div className="bg-(--color-bg-surface) border border-(--color-border) rounded-xl p-5">
        <div className="flex items-start justify-between gap-4">
          <div>
            <div className="flex items-center gap-2.5">
              <h1 className="text-xl font-bold text-(--color-text-primary)">
                {strategy.name}
              </h1>
              <span
                className={cn(
                  "inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-semibold uppercase",
                  strategy.is_active
                    ? "bg-(--color-positive)/10 text-(--color-positive)"
                    : "bg-(--color-bg-elevated) text-(--color-text-secondary)",
                )}
              >
                <span
                  className={cn(
                    "w-1.5 h-1.5 rounded-full",
                    strategy.is_active ? "bg-(--color-positive)" : "bg-(--color-text-secondary)/40",
                  )}
                />
                {strategy.is_active ? "Active" : "Inactive"}
              </span>
            </div>
            {symbols.length > 0 && (
              <div className="flex flex-wrap gap-1.5 mt-2">
                {symbols.map((s) => (
                  <span
                    key={s}
                    className="text-[11px] bg-(--color-accent-soft) text-(--color-accent) rounded-md px-2 py-0.5 font-medium"
                  >
                    {s}
                  </span>
                ))}
              </div>
            )}
          </div>

          <div className="flex items-center gap-1.5 shrink-0">
            <button
              onClick={() => toggleMutation.mutate(strategy.id)}
              disabled={toggleMutation.isPending}
              className={cn(
                "flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors",
                strategy.is_active
                  ? "bg-(--color-negative)/10 text-(--color-negative) hover:bg-(--color-negative)/20"
                  : "bg-(--color-positive)/10 text-(--color-positive) hover:bg-(--color-positive)/20",
              )}
            >
              <Power className="w-3.5 h-3.5" />
              {strategy.is_active ? "Deactivate" : "Activate"}
            </button>
            {showConfirm ? (
              <div className="flex items-center gap-1 ml-1">
                <button
                  onClick={handleDelete}
                  disabled={deleteMutation.isPending}
                  className="px-2.5 py-1.5 rounded-lg text-xs font-medium bg-(--color-negative)/10 text-(--color-negative) hover:bg-(--color-negative)/20 transition-colors"
                >
                  {deleteMutation.isPending ? "..." : "Confirm Delete"}
                </button>
                <button
                  onClick={() => setShowConfirm(false)}
                  className="px-2.5 py-1.5 rounded-lg text-xs text-(--color-text-secondary) hover:bg-(--color-bg-elevated) transition-colors"
                >
                  Cancel
                </button>
              </div>
            ) : (
              <button
                onClick={() => setShowConfirm(true)}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium text-(--color-text-secondary) hover:bg-(--color-negative)/10 hover:text-(--color-negative) transition-colors"
              >
                <Trash2 className="w-3.5 h-3.5" />
                Delete
              </button>
            )}
          </div>
        </div>

        {/* Performance summary */}
        {stats && stats.total_trades > 0 && (
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-4 pt-4 border-t border-(--color-border)/50">
            <div className="bg-(--color-bg-elevated)/50 rounded-lg px-3 py-2">
              <p className="text-[10px] text-(--color-text-secondary)">Total P&L</p>
              <p className={cn(
                "text-sm font-semibold font-mono",
                stats.total_pnl >= 0 ? "text-(--color-positive)" : "text-(--color-negative)",
              )}>
                {stats.total_pnl >= 0 ? "+" : ""}${stats.total_pnl.toFixed(2)}
              </p>
            </div>
            <div className="bg-(--color-bg-elevated)/50 rounded-lg px-3 py-2">
              <p className="text-[10px] text-(--color-text-secondary)">Win Rate</p>
              <div className="flex items-center gap-1">
                <Target className="w-3 h-3 text-(--color-accent)" />
                <p className="text-sm font-semibold font-mono text-(--color-text-primary)">
                  {stats.win_rate.toFixed(1)}%
                </p>
              </div>
            </div>
            <div className="bg-(--color-bg-elevated)/50 rounded-lg px-3 py-2">
              <p className="text-[10px] text-(--color-text-secondary)">Trades</p>
              <p className="text-sm font-semibold font-mono text-(--color-text-primary)">
                {stats.total_trades}
              </p>
            </div>
            <div className="bg-(--color-bg-elevated)/50 rounded-lg px-3 py-2">
              <p className="text-[10px] text-(--color-text-secondary)">Profit Factor</p>
              <p className={cn(
                "text-sm font-semibold font-mono",
                stats.profit_factor >= 1 ? "text-(--color-positive)" : "text-(--color-negative)",
              )}>
                {stats.profit_factor.toFixed(2)}
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Tab bar */}
      <div className="border-b border-(--color-border)">
        <div className="flex gap-6">
          {TABS.map((tab) => {
            const Icon = tab.icon;
            return (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key)}
                className={cn(
                  "pb-2.5 text-sm font-medium transition-colors border-b-2 -mb-px flex items-center gap-1.5",
                  activeTab === tab.key
                    ? "border-(--color-accent) text-(--color-accent)"
                    : "border-transparent text-(--color-text-secondary) hover:text-(--color-text-primary)",
                )}
              >
                <Icon className="w-3.5 h-3.5" />
                {tab.label}
                <Tooltip icon text={tab.tip} />
              </button>
            );
          })}
        </div>
      </div>

      {/* Tab content */}
      {activeTab === "signals" && (
        <div>
          <DataTable
            data={signals}
            columns={signalColumns}
            loading={signalsLoading}
            emptyMessage="No signals generated by this strategy yet."
          />
          {signalTotal > PAGE_SIZE && (
            <Pagination
              total={signalTotal}
              limit={PAGE_SIZE}
              offset={signalOffset}
              onChange={setSignalOffset}
            />
          )}
        </div>
      )}

      {activeTab === "strategy" && (
        <div className="grid grid-cols-1 lg:grid-cols-[minmax(280px,35%)_1fr] gap-6">
          <StrategyBacktestForm
            onSubmit={(req) => strategyBtMutation.mutate(req)}
            isLoading={strategyBtMutation.isPending}
            prefillStrategyId={strategy.id}
          />
          <StrategyBacktestResults
            result={strategyBtResult}
            isLoading={strategyBtMutation.isPending}
            error={strategyBtMutation.error}
          />
        </div>
      )}
    </div>
  );
}
