/**
 * Comprehensive list of crypto symbols with display names.
 * Covers top ~300 coins by market cap + popular tokens.
 * Sorted alphabetically by symbol.
 */
export interface CryptoEntry {
  symbol: string;
  name: string;
}

export const CRYPTO_LIST: CryptoEntry[] = [
  { symbol: "1INCH", name: "1inch Network" },
  { symbol: "AAVE", name: "Aave" },
  { symbol: "ACH", name: "Alchemy Pay" },
  { symbol: "ACX", name: "Across Protocol" },
  { symbol: "ADA", name: "Cardano" },
  { symbol: "AERO", name: "Aerodrome Finance" },
  { symbol: "AGIX", name: "SingularityNET" },
  { symbol: "AGLD", name: "Adventure Gold" },
  { symbol: "AIOZ", name: "AIOZ Network" },
  { symbol: "AJNA", name: "Ajna Protocol" },
  { symbol: "AKRO", name: "Akropolis" },
  { symbol: "AKT", name: "Akash Network" },
  { symbol: "ALGO", name: "Algorand" },
  { symbol: "ALPH", name: "Alephium" },
  { symbol: "ALICE", name: "My Neighbor Alice" },
  { symbol: "ALPHA", name: "Alpha Venture DAO" },
  { symbol: "ALT", name: "AltLayer" },
  { symbol: "AMP", name: "Amp" },
  { symbol: "ANKR", name: "Ankr" },
  { symbol: "ANT", name: "Aragon" },
  { symbol: "APE", name: "ApeCoin" },
  { symbol: "API3", name: "API3" },
  { symbol: "APT", name: "Aptos" },
  { symbol: "AR", name: "Arweave" },
  { symbol: "ARB", name: "Arbitrum" },
  { symbol: "ARKM", name: "Arkham" },
  { symbol: "ASTR", name: "Astar" },
  { symbol: "ATA", name: "Automata" },
  { symbol: "ATOM", name: "Cosmos" },
  { symbol: "AUDIO", name: "Audius" },
  { symbol: "AVAX", name: "Avalanche" },
  { symbol: "AXL", name: "Axelar" },
  { symbol: "AXS", name: "Axie Infinity" },
  { symbol: "BAL", name: "Balancer" },
  { symbol: "BAND", name: "Band Protocol" },
  { symbol: "BAT", name: "Basic Attention Token" },
  { symbol: "BCH", name: "Bitcoin Cash" },
  { symbol: "BEAM", name: "Beam" },
  { symbol: "BEL", name: "Bella Protocol" },
  { symbol: "BICO", name: "Biconomy" },
  { symbol: "BLUR", name: "Blur" },
  { symbol: "BLZ", name: "Bluzelle" },
  { symbol: "BNB", name: "BNB" },
  { symbol: "BNT", name: "Bancor" },
  { symbol: "BOME", name: "Book of Meme" },
  { symbol: "BOND", name: "BarnBridge" },
  { symbol: "BONK", name: "Bonk" },
  { symbol: "BSV", name: "Bitcoin SV" },
  { symbol: "BTC", name: "Bitcoin" },
  { symbol: "BTT", name: "BitTorrent" },
  { symbol: "BUSD", name: "Binance USD" },
  { symbol: "C98", name: "Coin98" },
  { symbol: "CAKE", name: "PancakeSwap" },
  { symbol: "CELO", name: "Celo" },
  { symbol: "CELR", name: "Celer Network" },
  { symbol: "CFX", name: "Conflux" },
  { symbol: "CHR", name: "Chromia" },
  { symbol: "CHZ", name: "Chiliz" },
  { symbol: "CKB", name: "Nervos Network" },
  { symbol: "COMP", name: "Compound" },
  { symbol: "CORE", name: "Core" },
  { symbol: "COS", name: "Contentos" },
  { symbol: "COTI", name: "COTI" },
  { symbol: "CRO", name: "Cronos" },
  { symbol: "CRV", name: "Curve DAO" },
  { symbol: "CSPR", name: "Casper" },
  { symbol: "CTK", name: "Shentu" },
  { symbol: "CTSI", name: "Cartesi" },
  { symbol: "CVX", name: "Convex Finance" },
  { symbol: "CYBER", name: "CyberConnect" },
  { symbol: "DAI", name: "Dai" },
  { symbol: "DAR", name: "Mines of Dalarnia" },
  { symbol: "DASH", name: "Dash" },
  { symbol: "DENT", name: "Dent" },
  { symbol: "DEXE", name: "DeXe" },
  { symbol: "DGB", name: "DigiByte" },
  { symbol: "DOGE", name: "Dogecoin" },
  { symbol: "DOT", name: "Polkadot" },
  { symbol: "DUSK", name: "Dusk" },
  { symbol: "DYDX", name: "dYdX" },
  { symbol: "DYM", name: "Dymension" },
  { symbol: "EDU", name: "Open Campus" },
  { symbol: "EGLD", name: "MultiversX" },
  { symbol: "ELF", name: "aelf" },
  { symbol: "ENA", name: "Ethena" },
  { symbol: "ENJ", name: "Enjin Coin" },
  { symbol: "ENS", name: "Ethereum Name Service" },
  { symbol: "EOS", name: "EOS" },
  { symbol: "ETC", name: "Ethereum Classic" },
  { symbol: "ETH", name: "Ethereum" },
  { symbol: "ETHFI", name: "Ether.fi" },
  { symbol: "ETHW", name: "EthereumPoW" },
  { symbol: "FET", name: "Fetch.ai" },
  { symbol: "FIDA", name: "Bonfida" },
  { symbol: "FIL", name: "Filecoin" },
  { symbol: "FLM", name: "Flamingo" },
  { symbol: "FLOKI", name: "Floki" },
  { symbol: "FLOW", name: "Flow" },
  { symbol: "FLR", name: "Flare" },
  { symbol: "FORTH", name: "Ampleforth Governance" },
  { symbol: "FTM", name: "Fantom" },
  { symbol: "FTT", name: "FTX Token" },
  { symbol: "FUN", name: "FunToken" },
  { symbol: "FXS", name: "Frax Share" },
  { symbol: "GAL", name: "Galxe" },
  { symbol: "GALA", name: "Gala" },
  { symbol: "GAS", name: "Gas" },
  { symbol: "GLMR", name: "Moonbeam" },
  { symbol: "GLM", name: "Golem" },
  { symbol: "GMT", name: "STEPN" },
  { symbol: "GMX", name: "GMX" },
  { symbol: "GNO", name: "Gnosis" },
  { symbol: "GNS", name: "Gains Network" },
  { symbol: "GRT", name: "The Graph" },
  { symbol: "GTC", name: "Gitcoin" },
  { symbol: "HBAR", name: "Hedera" },
  { symbol: "HFT", name: "Hashflow" },
  { symbol: "HIFI", name: "Hifi Finance" },
  { symbol: "HIGH", name: "Highstreet" },
  { symbol: "HNT", name: "Helium" },
  { symbol: "HOOK", name: "Hooked Protocol" },
  { symbol: "HOT", name: "Holo" },
  { symbol: "ICP", name: "Internet Computer" },
  { symbol: "ICX", name: "ICON" },
  { symbol: "ID", name: "SPACE ID" },
  { symbol: "IDEX", name: "IDEX" },
  { symbol: "ILV", name: "Illuvium" },
  { symbol: "IMX", name: "Immutable" },
  { symbol: "INJ", name: "Injective" },
  { symbol: "IOST", name: "IOST" },
  { symbol: "IOTA", name: "IOTA" },
  { symbol: "IOTX", name: "IoTeX" },
  { symbol: "JASMY", name: "JasmyCoin" },
  { symbol: "JOE", name: "Trader Joe" },
  { symbol: "JST", name: "JUST" },
  { symbol: "JTO", name: "Jito" },
  { symbol: "JUP", name: "Jupiter" },
  { symbol: "KAS", name: "Kaspa" },
  { symbol: "KAVA", name: "Kava" },
  { symbol: "KCS", name: "KuCoin Token" },
  { symbol: "KDA", name: "Kadena" },
  { symbol: "KLAY", name: "Klaytn" },
  { symbol: "KNC", name: "Kyber Network Crystal" },
  { symbol: "KSM", name: "Kusama" },
  { symbol: "LDO", name: "Lido DAO" },
  { symbol: "LEVER", name: "LeverFi" },
  { symbol: "LINA", name: "Linear Finance" },
  { symbol: "LINK", name: "Chainlink" },
  { symbol: "LIT", name: "Litentry" },
  { symbol: "LOOM", name: "Loom Network" },
  { symbol: "LPT", name: "Livepeer" },
  { symbol: "LQTY", name: "Liquity" },
  { symbol: "LRC", name: "Loopring" },
  { symbol: "LSK", name: "Lisk" },
  { symbol: "LTC", name: "Litecoin" },
  { symbol: "LUNA", name: "Terra" },
  { symbol: "LUNC", name: "Terra Classic" },
  { symbol: "MAGIC", name: "MAGIC" },
  { symbol: "MANA", name: "Decentraland" },
  { symbol: "MANTA", name: "Manta Network" },
  { symbol: "MASK", name: "Mask Network" },
  { symbol: "MATIC", name: "Polygon (old)" },
  { symbol: "MAV", name: "Maverick Protocol" },
  { symbol: "MBL", name: "MovieBloc" },
  { symbol: "MBOX", name: "MOBOX" },
  { symbol: "MDT", name: "Measurable Data Token" },
  { symbol: "MEME", name: "Memecoin" },
  { symbol: "METIS", name: "Metis" },
  { symbol: "MINA", name: "Mina Protocol" },
  { symbol: "MKR", name: "Maker" },
  { symbol: "MLN", name: "Enzyme" },
  { symbol: "MOVR", name: "Moonriver" },
  { symbol: "MTL", name: "Metal DAO" },
  { symbol: "MULTI", name: "Multichain" },
  { symbol: "MYRO", name: "Myro" },
  { symbol: "NEAR", name: "NEAR Protocol" },
  { symbol: "NEO", name: "Neo" },
  { symbol: "NEXO", name: "Nexo" },
  { symbol: "NFP", name: "NFPrompt" },
  { symbol: "NKN", name: "NKN" },
  { symbol: "NMR", name: "Numeraire" },
  { symbol: "NTRN", name: "Neutron" },
  { symbol: "OGN", name: "Origin Protocol" },
  { symbol: "OM", name: "MANTRA" },
  { symbol: "OMG", name: "OMG Network" },
  { symbol: "OMNI", name: "Omni Network" },
  { symbol: "ONE", name: "Harmony" },
  { symbol: "ONG", name: "Ontology Gas" },
  { symbol: "ONT", name: "Ontology" },
  { symbol: "OP", name: "Optimism" },
  { symbol: "ORBS", name: "Orbs" },
  { symbol: "ORDI", name: "ORDI" },
  { symbol: "OSMO", name: "Osmosis" },
  { symbol: "OXT", name: "Orchid" },
  { symbol: "PAXG", name: "PAX Gold" },
  { symbol: "PENDLE", name: "Pendle" },
  { symbol: "PEOPLE", name: "ConstitutionDAO" },
  { symbol: "PEPE", name: "Pepe" },
  { symbol: "PERP", name: "Perpetual Protocol" },
  { symbol: "PHB", name: "Phoenix" },
  { symbol: "PIXEL", name: "Pixels" },
  { symbol: "POLYX", name: "Polymesh" },
  { symbol: "POND", name: "Marlin" },
  { symbol: "PORTAL", name: "Portal" },
  { symbol: "POWR", name: "Powerledger" },
  { symbol: "PYTH", name: "Pyth Network" },
  { symbol: "QI", name: "BENQI" },
  { symbol: "QKC", name: "QuarkChain" },
  { symbol: "QNT", name: "Quant" },
  { symbol: "QTUM", name: "Qtum" },
  { symbol: "RAD", name: "Radicle" },
  { symbol: "RARE", name: "SuperRare" },
  { symbol: "RDNT", name: "Radiant Capital" },
  { symbol: "REEF", name: "Reef" },
  { symbol: "REN", name: "Ren" },
  { symbol: "REQ", name: "Request" },
  { symbol: "RLC", name: "iExec RLC" },
  { symbol: "RNDR", name: "Render" },
  { symbol: "RONIN", name: "Ronin" },
  { symbol: "ROSE", name: "Oasis Network" },
  { symbol: "RPL", name: "Rocket Pool" },
  { symbol: "RSR", name: "Reserve Rights" },
  { symbol: "RUNE", name: "THORChain" },
  { symbol: "RVN", name: "Ravencoin" },
  { symbol: "SAND", name: "The Sandbox" },
  { symbol: "SATS", name: "1000SATS" },
  { symbol: "SC", name: "Siacoin" },
  { symbol: "SEI", name: "Sei" },
  { symbol: "SFP", name: "SafePal" },
  { symbol: "SHIB", name: "Shiba Inu" },
  { symbol: "SKL", name: "SKALE" },
  { symbol: "SLP", name: "Smooth Love Potion" },
  { symbol: "SNT", name: "Status" },
  { symbol: "SNX", name: "Synthetix" },
  { symbol: "SOL", name: "Solana" },
  { symbol: "SPELL", name: "Spell Token" },
  { symbol: "SSV", name: "ssv.network" },
  { symbol: "STORJ", name: "Storj" },
  { symbol: "STMX", name: "StormX" },
  { symbol: "STRAX", name: "Stratis" },
  { symbol: "STX", name: "Stacks" },
  { symbol: "SUI", name: "Sui" },
  { symbol: "SUN", name: "Sun" },
  { symbol: "SUPER", name: "SuperVerse" },
  { symbol: "SUSHI", name: "SushiSwap" },
  { symbol: "SXP", name: "Solar" },
  { symbol: "SYN", name: "Synapse" },
  { symbol: "T", name: "Threshold" },
  { symbol: "TAO", name: "Bittensor" },
  { symbol: "THETA", name: "Theta Network" },
  { symbol: "TIA", name: "Celestia" },
  { symbol: "TLM", name: "Alien Worlds" },
  { symbol: "TNSR", name: "Tensor" },
  { symbol: "TON", name: "Toncoin" },
  { symbol: "TRB", name: "Tellor" },
  { symbol: "TROY", name: "TROY" },
  { symbol: "TRU", name: "TrueFi" },
  { symbol: "TRX", name: "TRON" },
  { symbol: "TUSD", name: "TrueUSD" },
  { symbol: "TWT", name: "Trust Wallet Token" },
  { symbol: "UMA", name: "UMA" },
  { symbol: "UNI", name: "Uniswap" },
  { symbol: "USDC", name: "USD Coin" },
  { symbol: "USDD", name: "USDD" },
  { symbol: "USDT", name: "Tether" },
  { symbol: "USTC", name: "TerraClassicUSD" },
  { symbol: "UTK", name: "xMoney" },
  { symbol: "VET", name: "VeChain" },
  { symbol: "VOXEL", name: "Voxies" },
  { symbol: "VTHO", name: "VeThor" },
  { symbol: "W", name: "Wormhole" },
  { symbol: "WAXP", name: "WAX" },
  { symbol: "WIF", name: "dogwifhat" },
  { symbol: "WIN", name: "WINkLink" },
  { symbol: "WLD", name: "Worldcoin" },
  { symbol: "WOO", name: "WOO" },
  { symbol: "XAI", name: "Xai" },
  { symbol: "XEC", name: "eCash" },
  { symbol: "XEM", name: "NEM" },
  { symbol: "XLM", name: "Stellar" },
  { symbol: "XMR", name: "Monero" },
  { symbol: "XNO", name: "Nano" },
  { symbol: "XRP", name: "XRP" },
  { symbol: "XTZ", name: "Tezos" },
  { symbol: "XVG", name: "Verge" },
  { symbol: "XVS", name: "Venus" },
  { symbol: "YFI", name: "yearn.finance" },
  { symbol: "YGG", name: "Yield Guild Games" },
  { symbol: "ZEC", name: "Zcash" },
  { symbol: "ZEN", name: "Horizen" },
  { symbol: "ZEPH", name: "Zephyr Protocol" },
  { symbol: "QUBIC", name: "Qubic" },
  { symbol: "RIO", name: "Realio Network" },
  { symbol: "ORAI", name: "Oraichain" },
  { symbol: "ABX", name: "AlphBanX" },
  { symbol: "APAD", name: "AlphPad" },
  { symbol: "EX", name: "Elexium" },
  { symbol: "AYIN", name: "Ayin" },
  { symbol: "ZETA", name: "ZetaChain" },
  { symbol: "ZIL", name: "Zilliqa" },
  { symbol: "ZK", name: "ZKsync" },
  { symbol: "ZRO", name: "LayerZero" },
  { symbol: "ZRX", name: "0x" },
];

/** Quick lookup map: symbol → name */
export const CRYPTO_NAME_MAP: Record<string, string> = Object.fromEntries(
  CRYPTO_LIST.map((c) => [c.symbol, c.name]),
);
